#!/bin/bash
set -e

export BIND_IP=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
export BROADCAST_IP=`curl http://169.254.169.254/latest/meta-data/public-ipv4`

/opt/cloudurable/bin/cassandra-cloud -cluster-name test \
                -client-address  ${BIND_IP} \
                -cluster-address  ${BIND_IP} \
                -cluster-seeds 10.2.1.10,10.2.2.10 \
                -cluster-broadcast-address ${BROADCAST_IP} \
                -snitch Ec2MultiRegionSnitch


/bin/systemctl restart  cassandra

